import { ScenarioWithQuestions } from '@/types';

export const SUBWAY_TOUR_SCENARIO: ScenarioWithQuestions = {
  id: 'subway-tour-001',
  title: 'NYC Subway 360° Platform Safety Tour',
  description: 'Experience the New York City subway system in immersive 360°. Test your situational awareness and platform safety knowledge as a passenger.',
  video_url: '/videos/subway360.mp4',
  thumbnail_url: 'https://images.unsplash.com/photo-1569168075631-7f0deb06e879?w=800&q=80',
  duration_seconds: 31,
  published: true,
  created_at: new Date().toISOString(),
  questions: [
    {
      id: 'st-q001',
      scenario_id: 'subway-tour-001',
      sort_order: 1,
      timestamp_seconds: 2.5,
      question_text: 'You just entered the subway platform. What is the first thing you should do?',
      option_a: 'Check your phone and wait near the platform edge for the train.',
      option_b: 'Orient yourself — locate the yellow safety line, exits, and emergency intercoms.',
      correct_option: 'b',
      explanation: 'Situational awareness starts the moment you enter the platform. Knowing exit locations and keeping distance from the edge are the foundations of platform safety.',
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'st-q002',
      scenario_id: 'subway-tour-001',
      sort_order: 2,
      timestamp_seconds: 5.5,
      question_text: 'How far from the platform edge should you stand while waiting for a train?',
      option_a: 'As close as possible so you can board quickly when the train arrives.',
      option_b: 'Behind the yellow safety line — at least 3 feet from the edge.',
      correct_option: 'b',
      explanation: 'Standing behind the yellow safety line protects you from train wind gusts, accidental bumps from other passengers, and emergency situations. Never step over it until the train has fully stopped.',
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'st-q003',
      scenario_id: 'subway-tour-001',
      sort_order: 3,
      timestamp_seconds: 8.5,
      question_text: 'You see an unattended bag left on a bench for over 10 minutes. What do you do?',
      option_a: 'Open or move the bag to check if it belongs to someone nearby.',
      option_b: 'Do not touch it — alert an MTA employee or police immediately and move away.',
      correct_option: 'b',
      explanation: 'Never touch, open, or move an unattended package. Follow the "See Something, Say Something" protocol — alert authorities and move away from the area.',
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'st-q004',
      scenario_id: 'subway-tour-001',
      sort_order: 4,
      timestamp_seconds: 11.5,
      question_text: 'The train is approaching. Passengers are crowding toward the edge. What should you do?',
      option_a: 'Push forward so you can board first before the crowd gets worse.',
      option_b: 'Step back, let the train stop fully and doors open before moving toward them.',
      correct_option: 'b',
      explanation: 'Rushing toward the train as it arrives is a leading cause of platform injuries. Wait for the train to stop completely and let exiting passengers off before boarding.',
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'st-q005',
      scenario_id: 'subway-tour-001',
      sort_order: 5,
      timestamp_seconds: 14.5,
      question_text: 'You hear the emergency alarm sound on the platform. What is your immediate action?',
      option_a: 'Wait and see if the alarm stops on its own before doing anything.',
      option_b: 'Stay calm, do not use elevators, follow exit signs, and alert MTA staff.',
      correct_option: 'b',
      explanation: 'Emergency alarms require immediate calm action. Never use elevators during emergencies. Follow posted exit signs, stay calm to avoid stampedes, and report to MTA personnel.',
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'st-q006',
      scenario_id: 'subway-tour-001',
      sort_order: 6,
      timestamp_seconds: 17.5,
      question_text: 'You see someone holding the subway doors open to wait for their friend. What is the risk?',
      option_a: 'No real risk — doors are designed to handle being held open briefly.',
      option_b: 'It delays all trains on the line and can trigger a door sensor fault, halting service.',
      correct_option: 'b',
      explanation: 'Holding subway doors causes delays that cascade across the entire line. Modern door sensors can fault and require manual reset, causing significant service disruption for thousands of riders.',
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'st-q007',
      scenario_id: 'subway-tour-001',
      sort_order: 7,
      timestamp_seconds: 20.5,
      question_text: 'A person falls onto the tracks. What is the correct action?',
      option_a: 'Jump down to help pull them up before the train arrives.',
      option_b: 'Immediately wave down the tracks to alert the conductor and press the emergency intercom.',
      correct_option: 'b',
      explanation: 'Never jump onto the tracks — you put yourself at equal risk. The correct action is to alert the train operator by waving arms and activate the emergency intercom so power can be cut and the train stopped.',
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'st-q008',
      scenario_id: 'subway-tour-001',
      sort_order: 8,
      timestamp_seconds: 23.5,
      question_text: 'A person with a visual impairment is standing near the platform edge. You are a bystander. What do you do?',
      option_a: 'Assume they know what they are doing and do not interfere.',
      option_b: 'Calmly approach and offer assistance — ask if they need help before touching or guiding them.',
      correct_option: 'b',
      explanation: 'Always ask before assisting someone with a disability — they may have a preferred method or not need help. A simple "Can I help you?" is respectful and effective.',
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'st-q009',
      scenario_id: 'subway-tour-001',
      sort_order: 9,
      timestamp_seconds: 26.5,
      question_text: 'You are on a crowded train and feel unsafe due to aggressive behavior from another passenger. What do you do?',
      option_a: 'Confront the individual directly to resolve the situation quickly.',
      option_b: 'Move to a different car, alert the conductor via the intercom, or contact police at the next stop.',
      correct_option: 'b',
      explanation: 'Engaging aggressively with a threatening passenger escalates danger. The safe response is to remove yourself, use available communication tools, and involve authorities.',
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'st-q010',
      scenario_id: 'subway-tour-001',
      sort_order: 10,
      timestamp_seconds: 29.5,
      question_text: 'Which item is prohibited on the NYC subway?',
      option_a: 'Bicycles during off-peak hours.',
      option_b: 'Smoking, open flames, and hazardous materials — these are strictly forbidden.',
      correct_option: 'b',
      explanation: 'Smoking and hazardous materials are strictly prohibited on all MTA property. Bicycles are allowed during off-peak hours. Violating prohibited item rules can result in fines and jeopardize passenger safety.',
      points: 10,
      created_at: new Date().toISOString(),
    },
  ],
};

export const DEMO_SCENARIO: ScenarioWithQuestions = {
  id: 'demo-scenario-001',
  title: 'Handling a Difficult Customer at the Fare Gate',
  description: 'You are a station agent at a busy NYC subway station. A customer approaches your booth frustrated about a MetroCard issue. Navigate this interaction professionally.',
  video_url: process.env.NEXT_PUBLIC_VIDEO_URL || 'https://cdn.aframe.io/360-image-gallery-boilerplate/img/city.mp4',
  thumbnail_url: 'https://images.unsplash.com/photo-1569168075631-7f0deb06e879?w=800&q=80',
  duration_seconds: 180,
  published: true,
  created_at: new Date().toISOString(),
  questions: [
    {
      id: 'q001',
      scenario_id: 'demo-scenario-001',
      sort_order: 1,
      timestamp_seconds: 15,
      question_text: "A customer runs up to you shouting 'My MetroCard didn't work and I missed my train! Fix it NOW!' What do you do first?",
      option_a: "Tell them to calm down and lower their voice before you help them.",
      option_b: "Acknowledge their frustration calmly: 'I understand, let me look into that right away.'",
      correct_option: 'b',
      explanation: "De-escalation always starts with acknowledgment, not correction. Telling someone to 'calm down' typically increases tension and puts you in an adversarial position.",
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'q002',
      scenario_id: 'demo-scenario-001',
      sort_order: 2,
      timestamp_seconds: 32,
      question_text: "The customer hands you their MetroCard. Your reader shows it has a $0 balance. The customer insists they just loaded $20. What do you do?",
      option_a: "Tell them 'The card shows $0, there's nothing I can do. They need to call 511.'",
      option_b: "Say 'I can see your balance shows $0 right now. Let me check if there's a pending transaction and give you the MTA refund process.'",
      correct_option: 'b',
      explanation: "Never leave a customer with no path forward. Always provide the next step. Referring to 511 without context feels dismissive. Offering to investigate first shows good faith.",
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'q003',
      scenario_id: 'demo-scenario-001',
      sort_order: 3,
      timestamp_seconds: 50,
      question_text: "A customer in a wheelchair approaches and says the elevator to the platform is broken. They're going to be late for a medical appointment. What is your priority action?",
      option_a: "Apologize and give them the MTA accessibility hotline number.",
      option_b: "Immediately radio the situation to your supervisor, offer to call ADA assistance, and tell the customer you are actively working on getting them help.",
      correct_option: 'b',
      explanation: "Accessibility situations require immediate escalation and active engagement, not just directing someone to a phone number. ADA compliance means you must take action, not just document.",
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'q004',
      scenario_id: 'demo-scenario-001',
      sort_order: 4,
      timestamp_seconds: 68,
      question_text: "A customer says they found a backpack left unattended on the platform for over 20 minutes. How do you respond?",
      option_a: "Thank them, radio it in as a suspicious package per MTA protocol, and ask the customer to move away from the area.",
      option_b: "Go check the bag yourself to see if it's really suspicious before calling it in.",
      correct_option: 'a',
      explanation: "MTA policy is clear: never approach or inspect unattended packages. Radio immediately, follow the See Something Say Something protocol, and manage crowd safety. Never investigate yourself.",
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'q005',
      scenario_id: 'demo-scenario-001',
      sort_order: 5,
      timestamp_seconds: 85,
      question_text: "A tourist asks you which train goes to JFK airport. There is a long line of other customers behind them. What do you do?",
      option_a: "Quickly say 'Take the A train' and wave them toward the platform to keep the line moving.",
      option_b: "Give them accurate directions: 'Take the A train to Howard Beach, then the AirTrain to JFK. Takes about 60 minutes. You'll need a separate AirTrain ticket.'",
      correct_option: 'b',
      explanation: "Speed that causes a customer to board the wrong train wastes more time than 15 extra seconds of correct information. Accurate directions are non-negotiable even when busy.",
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'q006',
      scenario_id: 'demo-scenario-001',
      sort_order: 6,
      timestamp_seconds: 102,
      question_text: "A visibly intoxicated person is sitting on the platform floor, bothering other passengers. They are not being violent. What is the correct response?",
      option_a: "Announce over the PA system that they must leave or police will be called.",
      option_b: "Approach calmly from a safe distance, assess their condition, radio for assistance, and if they are unresponsive or ill, call for medical help immediately.",
      correct_option: 'b',
      explanation: "Public announcements escalate situations and embarrass individuals, which can turn non-violent situations violent. Assessment and proper escalation through channels is the protocol.",
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'q007',
      scenario_id: 'demo-scenario-001',
      sort_order: 7,
      timestamp_seconds: 118,
      question_text: "A customer is filming you with their phone during a heated argument about a fare dispute. How do you respond?",
      option_a: "Ask them to stop filming and threaten to end the conversation if they don't.",
      option_b: "Continue to assist them professionally. Members of the public have the right to film in public spaces. Your conduct should always be the same whether filmed or not.",
      correct_option: 'b',
      explanation: "Demanding someone stop filming often escalates the situation dramatically and can become a news story. MTA employees must maintain consistent professional conduct at all times.",
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'q008',
      scenario_id: 'demo-scenario-001',
      sort_order: 8,
      timestamp_seconds: 135,
      question_text: "A child, approximately 7 years old, is standing alone on the platform crying. They say they can't find their parent. What is your immediate first action?",
      option_a: "Make a PA announcement asking the parent to come to your booth.",
      option_b: "Bring the child to a safe, visible area near your booth, radio for assistance, and stay with the child while looking for the parent. Do not leave the child alone.",
      correct_option: 'b',
      explanation: "Child safety is paramount. The child must never be left alone. A PA announcement is secondary — physical safety and supervision come first. Radio for backup immediately.",
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'q009',
      scenario_id: 'demo-scenario-001',
      sort_order: 9,
      timestamp_seconds: 152,
      question_text: "During rush hour, an overcrowded platform situation is developing. Passengers are dangerously close to the edge. What do you do?",
      option_a: "Wait to see if the next train resolves the crowding before escalating.",
      option_b: "Immediately radio the situation to your supervisor and the train operator, make a PA announcement asking customers to move back from the platform edge, and prepare to implement platform crowd management protocol.",
      correct_option: 'b',
      explanation: "Platform overcrowding is a life-safety situation requiring immediate action. Waiting to see if it resolves itself is never acceptable when passengers are near the platform edge.",
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: 'q010',
      scenario_id: 'demo-scenario-001',
      sort_order: 10,
      timestamp_seconds: 168,
      question_text: "Your shift ends in 5 minutes and there is still a long line of customers. Your relief has not arrived. What do you do?",
      option_a: "Close your window at shift end time, leave a note, and exit. You are not responsible for the relief's tardiness.",
      option_b: "Stay at your post, radio your supervisor immediately to report the no-show, and continue serving customers until officially relieved.",
      correct_option: 'b',
      explanation: "MTA protocol requires you to remain on duty until officially relieved. You may never abandon your post. Report the no-show through proper channels while continuing to serve the public.",
      points: 10,
      created_at: new Date().toISOString(),
    },
  ],
};

export async function getScenario(id: string): Promise<ScenarioWithQuestions | null> {
  if (id === 'subway-tour-001') return SUBWAY_TOUR_SCENARIO;
  if (id === 'demo-scenario-001' || !process.env.NEXT_PUBLIC_SUPABASE_URL) {
    return DEMO_SCENARIO;
  }
  return DEMO_SCENARIO; // fallback
}
